### PR TITLE
Convert IJulia notebooks to Pluto.jl and update CI

### PR DESCRIPTION
**Pull request by lassepe**
The primary contribution of this PR is the following: migrate all the example notebooks to Pluto.jl.

In order to facilitate this migration, I did several things:

- I migrated the entire CI to GitHub action; Travis is no longer used for generating docs. See `.github//workflows/Docs.yml` for details.
- I added a step to `docs/make.jl` which uses [PlutoSliderServer.jl](https://github.com/JuliaPluto/PlutoSliderServer.jl) to render a static HTML preview of the notebooks in `notebooks/` to `docs/build/notebooks`. These artifacts are now uploaded together with the docs and linked as "tutorials" on the main page.
- I also enabled the `push_preview` feature in `Documenter.docdeploy`. This way, the CI now generates a preview version of the updated doc with every PR under `https://juliapomdp.github.io/ParticleFilters.jl/previews/PR<PRnumber>`; i.e., for this PR you can find the preview here: https://juliapomdp.github.io/ParticleFilters.jl/previews/PR40

### CODE REVIEW

**Review by zsunberg — COMMENTED** [review]
Nice! This is very cool, but the problem is that the Pluto notebooks do not render on github, so people cannot see how it works. Is there a way to view them on the web?

**Comment by lassepe** [comment]
Hmm, that is a good point. There is an option to export a static HTML file which we could include in the repo. Natively, GitHub does not support to render Pluto notebooks since they are just `jl` files (they only contains the code, not the output). We could probably have a CI job that renders the static HTML files together with the documentation.

**Comment by zsunberg** [comment]
That would be ok. Do you know what other people do? What about markdown? Is it possible to use an md file as the only save file for Pluto?

**Comment by lassepe** [comment]
I have not seen other people do this yet. Currently, there seems to be no option to export to markdown; only static HTML or PDF.

**Comment by zsunberg** [comment]
Could we put a code line at the end of the pluto notebook that saves it as a pdf so that it gets updated whenever someone edits it? (I am suggesting pdf because I am worried about the images being saved separately, which might be a pain in git, if you output as html)

**Comment by mossr** [comment]
Pluto just merged a PR that fixes image embeddings in HTML (https://github.com/fonsp/Pluto.jl/pull/457). Note it's not yet part of a Pluto tagged release, but you can get it on master.

I tried the fix with images generated from TikzPictures, PyPlot, D3Trees, and PGFPlots and it works flawlessly!

**Comment by lassepe** [comment]
@mossr Thank you for the heads up. I'll look at this again once `Pluto.jl` has tagged a new release with that fix.

**Comment by lassepe** [comment]
I created https://github.com/fonsp/Pluto.jl/issues/506 to discuss our use case since I can't see a way to do what we need right now (it seems like it might work already but the HTML export is implemented on the js side, not in Julia, I believe). For now, I am converting this PR to a draft since it should not be merged as is.

**Comment by mykelk** [comment]
@lassepe are you interested in reexploring this at this point? It looks like the infrastructure is in place now on the Pluto side.

**Comment by lassepe** [comment]
Thanks for the reminder! Yeah, I think this would still be a valuable addition. I am pretty busy these days so if someone gets to this before me, please don't wait. I may take a stab after ICRA otherwise

**Comment by lassepe** [comment]
This turned out to be less annoying than I thought; at least locally. @zsunberg do you know how we can deploy a test version of the docs through the CI to see if it also works  there?

**Comment by lassepe** [comment]
In fact, it looks like the CI does not depoy the docs at all? Did you do that manually in the past, @zsunberg?

**Comment by zsunberg** [comment]
🤷

**Comment by zsunberg** [comment]
(sorry my earlier response was just my immediate reaction from my phone, haha).

No, I have not deployed them manually before, but this repo is old enough that the procedure for auto-deployment may have changed considerably. So we probably will have to set it up again. I will look if I have time, but if someone else wants to take a stab at it, that would be much appreciated!

**Comment by lassepe** [comment]
This is ready for review/merge now. I updated the PR descriptions with a more complete list of changes because I had to do a few more things to do make this work.

Side note: @zsunberg The new `push_preview` feature may also be interesting for the main POMDPs.jl package.

**Comment by zsunberg** [comment]
Wow @lassepe , this looks amazing!! Thank you so much for this! I am taking a quick look at the notebooks and then will merge.

**Comment by zsunberg** [comment]
Ok, I looked at the notebooks quickly. One quick question:
Do we still want to use the Pkg.activate / Pkg.instatiate in the notebooks since Pluto apparently has its own version of that? https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management

One longer question that DOES NOT need to be fully answered before merging this since most seem to agree that it is a good idea, but it might make me feel better: Why are we switching to Pluto? Plusses I can see: (1) No hidden state (2) easier to maintain because file format has much less overhead. Are there other reasons?

(I was just off-put when I opened Pluto for this - probably because my old programming habits are so ingrained. For example, it is really unnerving to me that you can use variables defined *later* in the document for instance - that seems very dishonest.)

**Comment by lassepe** [comment]
1. We can switch to the Pluto internal package manager; in fact, probably we should. The only challenge that brings is that we can not simply do `include("path/to/notebook.jl")` in the CI but that is fixed if we add all the notebook dependencies to the tests.
2. I think the main reasons to use Pluto are that:
- The file format is just a Julia script that works also without Pluto
- Versioning it with git is easy and readable
- I agree that it is weird that cells can be in an arbitrary order (and I avoid that when I write notebooks). However, I generally feel that this is just a gimmick resulting from the fact that Pluto embraces functional programming: if you write your code in a function way without side-effects the computation graph is just a DAG and the cell position is arbitrary. Sometimes, it is useful to reorder cells for cleaner presentation; but usually it's just a (confusing) flex. The fact that Pluto *does* enforce a functional style   and that *execution order* does not matter is a very clear bonus in IMO
- The "state-less" approach makes it super easy to build intuition with interactive widgets. For example, when you move the slider that determines the number of particles in one of our notebooks, you can directly see how that affects estimation quality:

[](https://user-images.githubusercontent.com/10076790/235484912-b598c840-f50d-48df-9b1b-e8d079021578.mp4)

**Comment by mykelk** [comment]
I'm a fan of the Pluto approach. The Pluto package manager is the way to go here. Thanks for all your work on this! Did you have to do anything special to get the documentation working (e.g., adding some keys)?

**Comment by lassepe** [comment]
Because the notebook html rendering is now part of `docs/make.jl` this "just works" out of the box with the standard Documenter run. I had to update the `DOCUMENTER_KEY` secret and deploy key because they were in a weird state (automatic deployment of docs for this package must have been broken for a while) but that just follows the [usual procedure](https://documenter.juliadocs.org/stable/man/hosting/walkthrough/#Generating-an-SSH-Key)

**Comment by mykelk** [comment]
Cool. @zsunberg can go ahead and merge when he's happy!

**Comment by zsunberg** [comment]
Wow, thanks for all the work, @lassepe !

**Pull request merged**
