### PR TITLE
Big refactor 

### LINKED ISSUE #18: Separate prediction and update steps
Often times filtering is split into prediction and update steps. For particle filters, the prediction step consists of propagating the particle states forward according to the system dynamics. The update step consists of incorporating the measurement by weighting according to observation likelihood and resampling.

It may be more efficient to perform these steps together, but I at least think there should be an `update(filter, b, a)` function that simply propagates the states forward for the user. It's not hard for the user to do but it would be convenient to have such a function. Thoughts?

### PR DESCRIPTION
**Pull request by zsunberg**
This refactor makes many things nicer, including breaking up the basic particle filter update into 3 independent steps
1. Prediction
2. Reweighting
3. Resampling

It will also considerably improve the non-POMDPs.jl interface, and fix #18 

Most of the code is there, but I still need to do all the documentation.

### CODE REVIEW

**Comment by zsunberg** [comment]
Ok, I think this is ready. Most of it is documentation (which is kind of a pain to read in a PR - sorry about that). One of the main points besides restructuring the basic particle filter into the three steps outlined above is making this less-closely-tied to POMDPs.jl, so a lot of the documentation and new code focuses on usage without POMDPs.jl.

Basically, I am hoping that this becomes a gateway drug for POMDPs ;)

@rejuvyesh, @dressel, @MaximeBouton I don't expect you guys to do a thorough review of so much code, but just wanted to give you the chance to comment if you want to.

I'll make a compatibility PR to the AA228 project so that nothing breaks when this is merged and tagged.

**Comment by rejuvyesh** [comment]
We probably don't want to change the AA228 codebase too much and probably adding a `[compat]` to their `Project.toml`, limiting the version number should be fine?

**Review by rejuvyesh — APPROVED** [review]
LGTM :tada:

**Review by MaximeBouton — APPROVED** [review]

**Review by dressel — APPROVED** [review]
Wow! Big change, but I like the general idea. I appreciate beefing up the non-POMDPs.jl stuff.

I think it's cool that you parameterize by functions (like by the f and g functions). Is that new to 1.0? Is there any performance penalty to doing it that way?

**Comment by zsunberg** [comment]
Thanks for taking a look at it, guys.

@dressel that parameterization is for the sake of performance. If the compiler knows the function types, it can just link directly to the method that will be called instead of running dynamic dispatch at runtime.

**Pull request merged**
